package id.co.keriss.switching.ee;
// Generated Jun 17, 2015 9:38:51 PM by Hibernate Tools 3.2.2.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Account generated by hbm2java
 */
public class Account  implements java.io.Serializable {


     private Long id;
     private String number;
     private String type;
     private String currency;
     private Long saldo;
     private Set transaction = new HashSet(0);

    public Account() {
    }

    public Account(String number, String type, String currency, Long saldo, Set transaction) {
       this.number = number;
       this.type = type;
       this.currency = currency;
       this.saldo = saldo;
       this.transaction = transaction;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public String getNumber() {
        return this.number;
    }
    
    public void setNumber(String number) {
        this.number = number;
    }
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }
    public String getCurrency() {
        return this.currency;
    }
    
    public void setCurrency(String currency) {
        this.currency = currency;
    }
    public Long getSaldo() {
        return this.saldo;
    }
    
    public void setSaldo(Long saldo) {
        this.saldo = saldo;
    }
    public Set getTransaction() {
        return this.transaction;
    }
    
    public void setTransaction(Set transaction) {
        this.transaction = transaction;
    }




}


