package id.co.keriss.switching.ee;
// Generated Jun 17, 2015 9:38:51 PM by Hibernate Tools 3.2.2.GA



/**
 * Attachment generated by hbm2java
 */
public class Attachment  implements java.io.Serializable {


     private Long id;
     private byte[] content;
     private String type;
     private Messaging messaging;

    public Attachment() {
    }

    public Attachment(byte[] content, String type, Messaging messaging) {
       this.content = content;
       this.type = type;
       this.messaging = messaging;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public byte[] getContent() {
        return this.content;
    }
    
    public void setContent(byte[] content) {
        this.content = content;
    }
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }
    public Messaging getMessaging() {
        return this.messaging;
    }
    
    public void setMessaging(Messaging messaging) {
        this.messaging = messaging;
    }




}


