package id.co.keriss.switching.ee;
// Generated Jun 17, 2015 9:38:51 PM by Hibernate Tools 3.2.2.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import org.jpos.ee.User;

/**
 * Messaging generated by hbm2java
 */
public class Messaging  implements java.io.Serializable {


     private Long id;
     private String message;
     private String subject;
     private String status;
     private String voucher;
     private String destionationbank;
     private Date timestamp;
     private String passemail;
     private Merchant merchant;
     private User user;
     private Set attachment = new HashSet(0);

    public Messaging() {
    }

    public Messaging(String message, String subject, String status, String voucher, String destionationbank, Date timestamp, String passemail, Merchant merchant, User user, Set attachment) {
       this.message = message;
       this.subject = subject;
       this.status = status;
       this.voucher = voucher;
       this.destionationbank = destionationbank;
       this.timestamp = timestamp;
       this.status = status;
       this.passemail = passemail;
       this.merchant = merchant;
       this.user = user;
       this.attachment = attachment;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public String getMessage() {
        return this.message;
    }
    
    public void setMessage(String message) {
        this.message = message;
    }
    public String getSubject() {
        return this.subject;
    }
    
    public void setSubject(String subject) {
        this.subject = subject;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    public String getVoucher() {
        return this.voucher;
    }
    
    public void setVoucher(String voucher) {
        this.voucher = voucher;
    }
    public String getDestionationbank() {
        return this.destionationbank;
    }
    
    public void setDestionationbank(String destionationbank) {
        this.destionationbank = destionationbank;
    }
    public Date getTimestamp() {
        return this.timestamp;
    }
    
    public void setTimestamp(Date timestamp) {
        this.timestamp = timestamp;
    }
    public String getPassemail() {
        return this.passemail;
    }
    
    public void setPassemail(String passemail) {
        this.passemail = passemail;
    }
    public Merchant getMerchant() {
        return this.merchant;
    }
    
    public void setMerchant(Merchant merchant) {
        this.merchant = merchant;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public Set getAttachment() {
        return this.attachment;
    }
    
    public void setAttachment(Set attachment) {
        this.attachment = attachment;
    }




}


