package id.co.keriss.switching.ee;
// Generated Jun 17, 2015 9:38:51 PM by Hibernate Tools 3.2.2.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Module generated by hbm2java
 */
public class Module  implements java.io.Serializable {


     private Long id;
     private String name;
     private String type;
     private Module parent;
     private Set child = new HashSet(0);
     private Set moduleperm = new HashSet(0);

    public Module() {
    }

    public Module(String name, String type, Module parent, Set child, Set moduleperm) {
       this.name = name;
       this.type = type;
       this.parent = parent;
       this.child = child;
       this.moduleperm = moduleperm;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }
    public Module getParent() {
        return this.parent;
    }
    
    public void setParent(Module parent) {
        this.parent = parent;
    }
    public Set getChild() {
        return this.child;
    }
    
    public void setChild(Set child) {
        this.child = child;
    }
    public Set<Moduleperm> getModuleperm() {
        return this.moduleperm;
    }
    
    public void setModuleperm(Set moduleperm) {
        this.moduleperm = moduleperm;
    }




}


