package id.co.keriss.switching.ee;
// Generated Feb 22, 2015 1:06:10 AM by Hibernate Tools 3.2.2.GA



/**
 * Module generated by hbm2java
 */
public class ModuleVO  implements java.io.Serializable {


     /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	 private Long id;
	private String name;
     private String perms;

    public String getPerms() {
		return perms;
	}

	public void setPerms(String perms) {
		this.perms = perms;
	}

	public ModuleVO() {
    }

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

}


