package id.co.keriss.switching.ee;
// Generated Jun 17, 2015 9:38:51 PM by Hibernate Tools 3.2.2.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Point generated by hbm2java
 */
public class Point  implements java.io.Serializable {


     private Long id;
     private Long value;
     private Date timestamp;
     private Set transaction = new HashSet(0);

    public Point() {
    }

    public Point(Long value, Date timestamp, Set transaction) {
       this.value = value;
       this.timestamp = timestamp;
       this.transaction = transaction;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public Long getValue() {
        return this.value;
    }
    
    public void setValue(Long value) {
        this.value = value;
    }
    public Date getTimestamp() {
        return this.timestamp;
    }
    
    public void setTimestamp(Date timestamp) {
        this.timestamp = timestamp;
    }
    public Set getTransaction() {
        return this.transaction;
    }
    
    public void setTransaction(Set transaction) {
        this.transaction = transaction;
    }




}


